---
# Welcome to Dashy! To get started, run `docker compose up -d`
# You can configure your container here, by modifying this file
# If you need to download the Icons from GIT. Go to the root directory of Dashy and run the following command:
                # sudo git clone https://github.com/walkxcode/dashboard-icons.git
# This will create a dashboard-icons directory with all the png and svg files.

version: "3.8"
services:
  dashy:
    container_name: Dashy

    # Pull latest image
    image: lissy93/dashy

    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .

    # You can also use an image with a different tag, or pull from a different registry, e.g:
    # image: ghcr.io/lissy93/dashy or image: lissy93/dashy:3.0.0

    # Mapping data to the volume created for this service
    volumes:
      - dashy-data/config:/app/user-data
      - dashy-data/icons:/app/user-data/item-icons/

    # Set port that web service will be served on. Keep container port as 8080
    ports:
      - 4000:8080

    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1000            # Update to match your UID
      - GID=1000            # Update to match your GID.

    # Sets the service to restart always unless it is stopped manually.
    restart: unless-stopped

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - proxy

# Persistent volume which are stored at "/var/lib/docker/volumes"
volumes:
  dashy-data:

# Service will be place in the proxy network for NPM security
networks:
  proxy:
    external: true
