version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-server
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npmuser"
      DB_MYSQL_PASSWORD: "hFThAaIjIdKypvMkD62F"
      DB_MYSQL_NAME: "npm1"
    volumes:
      - /home/miker/docker/npm/data:/data
      - /home/miker/docker/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - proxy

  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'hFThAaIjIdKypvMkD62F'
      MYSQL_DATABASE: 'npm1'
      MYSQL_USER: 'npmuser'
      MYSQL_PASSWORD: 'hFThAaIjIdKypvMkD62F'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - /home/miker/docker/npm/mysql:/var/lib/mysql
    networks:
      - proxy

networks:
  proxy:
    external: true
