version: '3'
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: elestio/uptime-kuma

    environment:
      - DB_TYPE=sqlite
      - DB_STORAGE=/app/data/uptime-kuma.db
      - SOFTWARE_VERSION_TAG=latest
      - URL=https://kuma.yourdomain.com         # Enter in your domain information

      volumes:
      - ~/docker/kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

#    labels:    # Uncomment if you need this for traefik.
#      - "traefik.enable=true"
#      - "traefik.http.routers.kuma.entrypoints=websecure"
#      - "traefik.http.routers.kuma.rule=Host(`kuma.yourdomain.com`)"
#      - "traefik.http.routers.kuma.tls=true"
#      - "traefik.http.routers.kuma.tls.certresolver=staging"
#      - "traefik.http.services.gitlab.loadBalancer.server.port=3001"

    restart: unless-stopped

    healthcheck:
      disable: true
    networks:
      - proxy

networks:
  proxy:
    external: true
